image: openjdk:11

stages:
  - lint
  - build

lint:
  stage: lint
    script:
      - apt-get update && apt-get install -y checkstyle
      - find src/ -name "*.java" -exec checkstyle -c /google_checks.xml {} \;
    allow_failure: true

build:
  stage: build
  script:
    - find . -name "*.java" | xargs javac -classpath build -d bin
  artifacts:
    paths:
      - build/
