image: openjdk:21

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - apt-get update && apt-get install -y checkstyle
    - /usr/bin/find src/ -name "*.java" -exec checkstyle -c ./checkstyle.xml {} \; > checkstyle_report.txt
    - cat checkstyle_report.txt
    - if egrep -q "\[ERROR\]" checkstyle_report.txt; then exit 1; fi
  allow_failure: true

build:
  stage: build
  script:
    - find . -name "*.java" | xargs javac -classpath build -d bin
  artifacts:
    paths:
      - build/
