image: openjdk:21

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.41/checkstyle-8.41-all.jar
    - java -jar checkstyle-8.41-all.jar -c /google_checks.xml src/
    - find src/ -name "*.java" -exec checkstyle -c ./checkstyle.xml {} \; > checkstyle_report.txt
    - cat checkstyle_report.txt
    - if egrep -q "\[ERROR\]" checkstyle_report.txt; then exit 1; fi
  allow_failure: true

build:
  stage: build
  script:
    - find . -name "*.java" | xargs javac -classpath build -d bin
  artifacts:
    paths:
      - build/
